### ISSUE TITLE
Create simple, reusable objects

### ISSUE THREAD

**Issue by drbassett** [dboone/rusty-checkers#2]
The Basic Object Oriented Belief System, professes the use of the simple objects and simple object interactions. Objects should be small, and have a focused purpose - no blobs allowed. Also, avoid abstract classes and multiple inheritance. Fortunately, the Rust designers were smart enough to not offer those features to start with, so those won't be an issue. Composition is a much better pattern. Finally, object interactions should be simple, and make sense. Two objects should not require 50 function calls back and forth to accomplish something simple.

**Comment by dboone** [comment]
:+1:

**Comment by crouserj** [comment]
Needs less men.

**Comment by dboone** [comment]
I think we have accomplished our goal of creating simple, reusable objects.
