### ISSUE TITLE
Clean up v0.1.0

### ISSUE THREAD

**Issue by dboone** [dboone/rusty-checkers#24]
[v0.1.0](https://github.com/dboone/rusty-checkers/releases/tag/v0.1.0) is playable but we can clean it up with style updates and addressing inconsequential compiler warnings.

Note that no major compiler warnings are present in [v0.1.0](https://github.com/dboone/rusty-checkers/releases/tag/v0.1.0). What kind of developers do you think we are?

**Comment by drbassett** [comment]
Retroactively closed by #25.
