### ISSUE TITLE
Double Jumps

### ISSUE THREAD

**Issue by crouserj** [dboone/rusty-checkers#31]
Are you required by the rules to perform all possible jumps (double/triple) when available, or can you choose to stop after 1 jump? As the game is written now, you can get away with a single jump when a double is available.

**Comment by drbassett** [comment]
This is legal. The rules only require that *a jump* be taken if one is available, not necessarily the longest possible jump.

**Comment by dboone** [comment]
This is up for debate. Dale and I have seen sources that agree with the current implementation, but I have also seen sources that have forced continuation where players must make the full jump sequence.
