### ISSUE TITLE
Draw

### ISSUE THREAD

**Issue by crouserj** [dboone/rusty-checkers#37]
Have you considered how to handle a draw, when neither player could win. How do you end the game? Set up for this is more than I have time to test right now, but I was wondering if it had been considered yet.

**Comment by drbassett** [comment]
Believe it or not, there is no such thing as a draw according to the official checkers rules. The [winning](https://github.com/dboone/rusty-checkers/blob/c6bf9d8bd98196189aa8095e10155d56864c5bb5/README.md#winning) section in our `readme` file covers all the possible game-stopping conditions - see it for the not-so-gory details.
