### ISSUE TITLE
Add Command Line User Input

### ISSUE THREAD

**Issue by drbassett** [dboone/rusty-checkers#6]
Moves should be specified using a list of file-rank pairs, where file-rank `a1` corresponds to row-column `(0, 0)`, `b2` to `(1, 1)`. The first pair will denote the piece to move. Subsequent pairs say where to move the piece. The input parser will have to be smart enough to know whether a move is a simple move or a jump move.

The file will be case insensitive.

Exact grammar:

```
file := [a-zA-Z]
rank := [1-9][0-9]*
Position := file rank
Move := Position (Whitespace Position)*
```

Example simple move: `a1 b2`

Example jump move: `c3 e5 c7`

**Comment by drbassett** [comment]
Moves should be specified using a list of file-rank pairs, where file-rank `a1` corresponds to row-column `(0, 0)`, `b2` to `(1, 1)`. The first pair will denote the piece to move. Subsequent pairs say where to move the piece. The input parser will have to be smart enough to know whether a move is a simple move or a jump move.

The file will be case insensitive.

Exact grammar:

```
file := [a-zA-Z]
rank := [1-9][0-9]*
Position := file rank
Move := Position (Whitespace Position)*
```

Example simple move: `a1 b2`

Example jump move: `c3 e5 c7`

**Comment by dboone** [comment]
> The input parser will have to be smart enough to know whether a move is a simple move or a jump move.

Will it though? In order to force players to take jumps we are forced to generate the jump tree for all of their pieces. One approach is to generate all possible moves for a given piece (the jump tree and all simple moves) and make sure that the player is taking a jump if the jump tree is not empty.

**Comment by dboone** [comment]
What about supporting file input to have the game run through certain game sequences?

**Comment by drbassett** [comment]
I could see file input being useful for a recording feature. Record your game, then play it back. We just have to abstract the input source
